# The first folder that contains all obsidian files
# Can be absent when toggles/compile_md == False
# On linux, use fullpath instead of ~/
#obsidian_folder_path_str: 'ci/test_vault/'

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Can be absent when toggles/compile_md == False
# On linux, use fullpath instead of ~/
obsidian_entrypoint_path_str: 'ci/test_vault/entrypoint.md'

# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# On linux, use fullpath instead of ~/
md_folder_path_str:  'tmp/md'

# Markdown entrypoint path
# This has to be md_folder_path_str + '/index.md' when toggles/compile_md == True
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# On linux, use fullpath instead of ~/
md_entrypoint_path_str: 'tmp/md/index.md'

# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# On linux, use fullpath instead of ~/
html_output_folder_path_str: 'tmp/html'

toggles:
  features:
    rss:
      enabled: False
      host_root: 'https://localhost:8088'
      styling: 
        show_icon: True
      channel: 
        title: '<test_title>'
        website_link: '<test_website_link>'
        description: '<test_website_description>'
        language_code: 'en-us'
        managing_editor: '<test_managing_editor>'
        web_master: '<test_web_master>'
      items:
        selector: 
          match_keys: ['yaml','tags', ['']]
          exclude_keys: ['yaml','tags', ['type/moc']]
          include_subfolders: ['rss']
          exclude_subfolders: ['.git', 'md', 'index_from_tags', 'obs.html','__src']
          exclude_files: ['not_created.html', 'index.html']
        description:
          selectors:
            - ['yaml','rss:description']
            - ['first-paragraphs', 2, '<br/><br/>']
            - ['first-header', 1]
        title: 
          selectors: 
            - ['yaml','rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']]
        publish_date: 
          selectors: 
            - ['yaml','rss:publish_date']
            - ['yaml_strip','tags',['date/']]
          iso_formatted: True
          format_string: '' #'%Y-%m-%d'
    
    create_index_from_dir_structure:
      enabled: True